<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
        td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
        tr:nth-child(even) { background-color: #dddddd; }
        .post-id{width:2%} .post-name{width:30%}

    </style>
</head>
<body>
<table>
    <tr>
        <th class="post-id">Id</th>
        <th class="post-name">Name</th>
        <th>Content</th>
    </tr>
    <?php
    /**
     * @var \Mageplaza\HelloWorld\Block\View $block
     */
    foreach ($block->getTopicList() as $key=>$topic){
        echo '<tr>
                    <td>'.$topic->getTopicId().'</td>
                    <td>'.$topic->getTitle().'</td>
                    <td>'.$topic->getContent().'</td>
                  </tr>';
    }
    ?>
</table>
</body>
</html>
